runtime: python3.9
api_version: 1
threadsafe: true
handlers:
  - url: /
    static_files: src/my-angular-app/index.html
    upload: src/my-angular-app/index.html
  - url: /
    static_dir: dist/my-angular-app
    
skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
