runtime: nodejs18
instance_class: F1
api_version: 1

handlers:
  # Serve index.html for requests to the root URL ("/")
  - url: /
    static_files: src/my-angular-app/index.html
    upload: src/my-angular-app/index.html

  # Serve static files from the "dist" directory
  - url: /
    static_dir: src/my-angular-app
