name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'  # Pin to a specific minor version of Node.js

      - name: Install dependencies
        working-directory: ./my-angular-app/
        run: npm install

      - name: Build Angular app
        working-directory: ./my-angular-app/
        run: npm run build -- --configuration=production

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./my-angular-app/dist

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          version: '482.0.0'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to App Engine
        run: |
          gcloud app deploy --quiet ./my-angular-app/app.yaml --project ${{ secrets.GCP_PROJECT_ID }} --promote

      - name: Open deployed application in browser
        run: gcloud app browse --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Get deployed application URL
        id: get-app-url
        run: echo "::set-output name=url::$(gcloud app browse --project=${{ secrets.GCP_PROJECT_ID }} --no-launch-browser --format='value(url)')"
