name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # adjust to your Node.js version

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-venv
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install awscli

      - name: Install Angular CLI and dependencies
        working-directory: ./my-angular-app/
        run: |
          npm install -g @angular/cli
          npm install

      - name: Build Angular app
        working-directory: ./my-angular-app/
        run: npm run build

      - name: Debugging - List directory contents
        run: ls -R

      - name: Zip build output
        run: zip -r my-angular-app.zip dist/*
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-angular-app
          path: my-angular-app.zip

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'  # replace with your AWS region, e.g., 'us-west-2'
        run: |
          aws s3 cp my-angular-app.zip s3://testing-angular27/  # replace with your S3 bucket name
          aws elasticbeanstalk create-application-version --application-name testing-angular --version-label $GITHUB_SHA --source-bundle S3Bucket="testing-angular27",S3Key="my-angular-app.zip"
          aws elasticbeanstalk update-environment --application-name testing-angular --environment-name testing-angular-env --version-label $GITHUB_SHA

      - name: Clean up
        run: rm -rf node_modules my-angular-app.zip
